version: '3'
services:
  auth:
    build:
      context: .
    command: python services/auth/__init__.py 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"

  ai:
    build:
      context: .
    command: python services/ai/main.py 0.0.0.0:5001
    volumes:
      - .:/code
    ports:
      - "5001:5001"

  search:
    build:
      context: .
    command: python services/search/main.py 0.0.0.0:5002
    volumes:
      - .:/code
    ports:
      - "5002:5002"